use crate::{
    i18n::Lang,
    wizard::{BuildConfig, DbBackend},
};
use anyhow::Result;
use std::{fs, path::Path};

// ── config.yml ────────────────────────────────────────────────────────────────

pub fn write_config(dir: &Path, cfg: &BuildConfig) -> Result<()> {
    let port = cfg.port_u16();
    let public_url = if cfg.domain.is_empty() {
        format!("http://{}:{}", cfg.host, port)
    } else {
        format!("https://{}", cfg.domain)
    };

    let db_block = match cfg.db_backend {
        DbBackend::Sqlite => format!("  backend: sqlite\n  sqlite_path: {}", cfg.sqlite_path),
        DbBackend::Postgres => format!("  backend: postgresql\n  url: {}", cfg.pg_url),
        DbBackend::Mysql => format!("  backend: mysql\n  url: {}", cfg.mysql_url),
    };

    let prov_block = if cfg.prov_enabled {
        format!("  enabled: true\n  shared_token: \"{}\"\n  header_name: X-KeyBase-Provision-Key\n  rate_limit_per_minute: 30",
            cfg.prov_token)
    } else {
        "  enabled: false".into()
    };

    let lang_code = match Lang::all().get(cfg.lang_idx) {
        Some(Lang::Ru) => "ru",
        Some(Lang::Es) => "es",
        _ => "en",
    };

    let yaml = format!(
        r#"# KeyBase Server — generated by KeyBase Builder
server:
  host: "{host}"
  port: {port}
  admin_host: "{host}"
  admin_port: {port}
  api_host: "{host}"
  api_port: {port}
  allow_remote_admin: {remote_admin}
  trust_proxy_headers: {trust_proxy}

cloudflare:
  enabled: {cloudflare}
  restore_visitor_ip: true
  require_https: false

api:
  public_base_url: "{public_url}"
  verify_rate_limit_per_minute: {rate_limit}
  allow_payload_ip_fallback: true

admin:
  public_base_url: "{public_url}"

database:
{db_block}

paths:
  data_dir: data

backup:
  directory: backups
  auto_enabled: true
  interval_minutes: 60
  keep_last: 24

provisioning:
{prov_block}

security:
  session_hours: 12
  confirm_minutes: 15
  password_min_length: 6
  login_attempts_per_10m: 10

protection:
  mode: warn
  anti_mode: warn
  anti_vm: true
  anti_vpn: true
  anti_proxy: true
  anti_debug: true
  anti_tamper: true
  anti_sandbox: true
  risk_weights:
    vpn: 25
    proxy: 25
    datacenter_asn: 20
    tor: 40
    suspicious_ua: 10
    timezone_geo_mismatch: 15
    too_fast_requests: 20
    missing_js_fingerprint: 30
    headless_browser: 25
    automation_flags: 25
    vm_or_emulator: 30
    debugger: 40
    low_behavior_entropy: 15
    sandbox: 60
    tamper: 80

public_ip:
  enabled: true
  cache_seconds: 300
  providers:
    - https://api.ipify.org
    - https://ifconfig.me/ip
    - https://ipv4.icanhazip.com

ui:
  update_banner_enabled: true

i18n:
  language: {lang_code}

debug: {debug}
"#,
        host = cfg.host,
        port = port,
        public_url = public_url,
        remote_admin = cfg.allow_remote_admin,
        trust_proxy = cfg.trust_proxy,
        cloudflare = cfg.cloudflare,
        rate_limit = cfg.rate_limit_u32(),
        db_block = db_block,
        prov_block = prov_block,
        lang_code = lang_code,
        debug = cfg.debug,
    );

    fs::write(dir.join("config.yml"), yaml)?;
    Ok(())
}

// ── .env ──────────────────────────────────────────────────────────────────────

pub fn write_env(dir: &Path) -> Result<()> {
    let env = "# KeyBase Server — environment overrides\n\
               # Secrets (session key, admin password hash) are generated on first run.\n\
               # Uncomment and set KEYBASE_DATA_DIR to override the data directory.\n\
               # KEYBASE_DATA_DIR=/var/lib/keybase\n";
    fs::write(dir.join(".env"), env)?;
    Ok(())
}

// ── Dockerfile ────────────────────────────────────────────────────────────────

pub fn write_docker(dir: &Path, cfg: &BuildConfig) -> Result<()> {
    let port = cfg.port_u16();

    let dockerfile = format!(
        r#"FROM python:3.12-slim

WORKDIR /app

# Install dependencies first (layer cache)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy server files
COPY . .

# Runtime directories
RUN mkdir -p data backups

EXPOSE {port}

HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:{port}/')" || exit 1

CMD ["python", "-m", "keybase"]
"#,
        port = port,
    );

    let dockerignore = "\
.git\n\
.venv\nvenv\n\
__pycache__\n*.pyc\n*.pyo\n\
data/*\nbackups/*\n\
*.log\n.env\n\
target\n";

    let compose = format!(
        r#"services:
  keybase:
    build: .
    container_name: keybase
    restart: unless-stopped
    ports:
      - "{port}:{port}"
    volumes:
      - keybase_data:/app/data
      - keybase_backups:/app/backups
      - ./config.yml:/app/config.yml:ro
      - ./.env:/app/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request; urllib.request.urlopen('http://localhost:{port}/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  keybase_data:
  keybase_backups:
"#,
        port = port,
    );

    fs::write(dir.join("Dockerfile"), dockerfile)?;
    fs::write(dir.join(".dockerignore"), dockerignore)?;
    fs::write(dir.join("docker-compose.yml"), compose)?;
    Ok(())
}

// ── NGINX config ──────────────────────────────────────────────────────────────

pub fn write_nginx(dir: &Path, cfg: &BuildConfig) -> Result<()> {
    let port = cfg.port_u16();
    let domain = if cfg.domain.is_empty() {
        "your-domain.com".to_string()
    } else {
        cfg.domain.clone()
    };

    let conf = format!(
        r#"# KeyBase — NGINX reverse proxy
# Place this file in /etc/nginx/sites-available/keybase
# Then: ln -s /etc/nginx/sites-available/keybase /etc/nginx/sites-enabled/
# And:  nginx -t && systemctl reload nginx

server {{
    listen 80;
    server_name {domain};

    # Redirect HTTP → HTTPS
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name {domain};

    # TLS — replace with your certificate paths
    ssl_certificate     /etc/ssl/certs/{domain}.crt;
    ssl_certificate_key /etc/ssl/private/{domain}.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    client_max_body_size 10M;

    location / {{
        proxy_pass         http://127.0.0.1:{port};
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }}
}}
"#,
        domain = domain,
        port = port,
    );

    fs::write(dir.join("nginx.conf"), conf)?;
    Ok(())
}

// ── systemd service ───────────────────────────────────────────────────────────

pub fn write_systemd(dir: &Path, cfg: &BuildConfig) -> Result<()> {
    let install_path = cfg.output_path().to_string_lossy().to_string();

    let service = format!(
        r#"[Unit]
Description=KeyBase License Key Server
After=network.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory={path}
ExecStart={path}/.venv/bin/python -m keybase
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=keybase

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full

[Install]
WantedBy=multi-user.target
"#,
        path = install_path,
    );

    fs::write(dir.join("keybase.service"), service)?;
    Ok(())
}

// ── README / Quick Start ──────────────────────────────────────────────────────

pub fn write_readme(dir: &Path, cfg: &BuildConfig) -> Result<()> {
    let port = cfg.port_u16();
    let host = &cfg.host;
    let _domain = if cfg.domain.is_empty() {
        format!("{}:{}", host, port)
    } else {
        cfg.domain.clone()
    };

    let docker_section = if cfg.gen_docker {
        format!(
            "\n## Docker\n\n```bash\ndocker compose up -d\n```\n\n\
Server will be available at http://{host}:{port}\n",
            host = host,
            port = port
        )
    } else {
        String::new()
    };

    let nginx_section = if cfg.gen_nginx {
        "\n## NGINX Reverse Proxy\n\n```bash\nsudo cp nginx.conf /etc/nginx/sites-available/keybase\n\
sudo ln -s /etc/nginx/sites-available/keybase /etc/nginx/sites-enabled/\nnginx -t && sudo systemctl reload nginx\n```\n".into()
    } else {
        String::new()
    };

    let systemd_section = if cfg.gen_systemd {
        format!(
"\n## systemd Service\n\n```bash\nsudo cp keybase.service /etc/systemd/system/\n\
sudo systemctl daemon-reload\nsudo systemctl enable --now keybase\nsudo systemctl status keybase\n```\n")
    } else {
        String::new()
    };

    let update_section = "\n## Updating\n\nTo upgrade an existing install, run Builder again and point it at the same folder. It will stop the running server, download the latest `Server-Portable.zip`, preserve `config.yml`, `.env`, `data/`, and `backups/`, and migrate databases automatically when the backend changes. If you want to hide the dashboard update strip, set `ui.update_banner_enabled: false` in `config.yml`.\n";

    let readme = format!(
        r#"# KeyBase Server

Self-hosted license key management server.

## Quick Start

### Windows
```bat
run.bat
```

### Linux
```bash
./run.sh
```

On first run, the server will ask you to create an admin account.

## URLs

| | URL |
|---|---|
| Admin panel | http://{host}:{port}/admin |
| API base    | http://{host}:{port}/api/v1 |
| Verify key  | POST http://{host}:{port}/api/v1/verify |
{docker_section}{nginx_section}{systemd_section}
{update_section}
## API Quick Reference

```http
POST /api/v1/verify
Content-Type: application/json

{{ "app_id": "default", "key": "XXXX-XXXX", "hwid": "...", "version": "1.0.0" }}
```

## Files

| File | Purpose |
|---|---|
| `config.yml` | Server configuration |
| `.env` | Secret overrides (auto-generated on first run) |
| `data/` | SQLite database and runtime data |
| `backups/` | Automatic backups |
{docker_files}{nginx_files}{systemd_files}
## Support

- Docs: https://github.com/{domain}
- Issues: https://github.com/{domain}/issues
"#,
        host = host,
        port = port,
        docker_section = docker_section,
        nginx_section = nginx_section,
        systemd_section = systemd_section,
        update_section = update_section,
        docker_files = if cfg.gen_docker {
            "| `Dockerfile` / `docker-compose.yml` | Docker deployment |\n"
        } else {
            ""
        },
        nginx_files = if cfg.gen_nginx {
            "| `nginx.conf` | NGINX reverse proxy config |\n"
        } else {
            ""
        },
        systemd_files = if cfg.gen_systemd {
            "| `keybase.service` | systemd service unit |\n"
        } else {
            ""
        },
        domain = if cfg.domain.is_empty() {
            "OWNER/key-base".to_string()
        } else {
            cfg.domain.clone()
        },
    );

    fs::write(dir.join("README.md"), readme)?;
    Ok(())
}

// ── Install log ───────────────────────────────────────────────────────────────

pub fn save_install_log(dir: &Path, log: &[String], elapsed_secs: f64) -> Result<()> {
    use chrono::Local;
    let ts = Local::now().format("%Y-%m-%d %H:%M:%S").to_string();
    let mut out =
        format!("KeyBase Builder — Install Log\nDate: {ts}\nDuration: {elapsed_secs:.1}s\n");
    out.push_str(&"─".repeat(60));
    out.push('\n');
    for line in log {
        out.push_str(line);
        out.push('\n');
    }
    fs::write(dir.join("install.log"), out)?;
    Ok(())
}
